# Generated by Django 2.2 on 2021-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(max_length=255)),
                ('ChannelTitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1023)),
                ('description', models.TextField()),
                ('thumbnailURL', models.URLField()),
                ('PublishedOn', models.DateField(blank=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
